
export type Item = {
  id: string;
  name: string;
  description: string;
  location: string;
  imageId: string;
  district: string;
  hasDetails?: boolean;
  lat?: number;
  lng?: number;
};

export type District = {
  id: string;
  name: string;
};

export const districts: District[] = [
  { id: 'tvm', name: 'Trivandrum' },
  { id: 'klm', name: 'Kollam' },
  { id: 'alp', name: 'Alappuzha' },
  { id: 'ktm', name: 'Kottayam' },
  { id: 'ekm', name: 'Ernakulam' },
  { id: 'tsr', name: 'Thrissur' },
  { id: 'pkd', name: 'Palakkad' },
  { id: 'idk', name: 'Idukki' },
  { id: 'wnd', name: 'Wayanad' },
  { id: 'kkd', name: 'Kozhikode' },
  { id: 'knr', name: 'Kannur' },
  { id: 'ksr', name: 'Kasargod' },
  { id: 'mnr', name: 'Munnar' },
];

export const attractions: Item[] = [
  {
    id: 'trivandrum_sree_padmanabhaswamy_temple',
    lat: 8.5241,
    lng: 76.9366,
    name: 'Sree Padmanabhaswamy Temple',
    description: 'Iconic Vishnu temple famous for its gold-plated gopuram. A divine ambience with a strict dress code for devotees.',
    location: 'Trivandrum',
    imageId: 'attraction-padmanabhaswamy-temple',
    district: 'Trivandrum',
    hasDetails: true,
  },
  {
    id: 'trivandrum_kovalam_beach',
    lat: 8.4004,
    lng: 76.9787,
    name: 'Kovalam Beach',
    description: 'A world-famous crescent beach known for its lighthouse, calm waters, and vibrant tourist scene.',
    location: 'Trivandrum',
    imageId: 'attraction-kovalam-beach',
    district: 'Trivandrum',
    hasDetails: true,
  },
  {
    id: 'trivandrum_ponmudi_hill_station',
    lat: 8.7599,
    lng: 77.1169,
    name: 'Ponmudi Hill Station',
    description: 'A scenic hill station in the Western Ghats known for tea estates, cool climate, and its 22 hairpin bends.',
    location: 'Trivandrum',
    imageId: 'attraction-ponmudi-hills',
    district: 'Trivandrum',
    hasDetails: true,
  },
  {
    id: 'trivandrum_veli_tourist_village',
    name: 'Veli Tourist Village',
    description: 'A scenic backwater park where the Veli lake meets the sea, popular for family outings and boating.',
    location: 'Trivandrum',
    imageId: 'attraction-veli-village',
    district: 'Trivandrum',
    hasDetails: true,
  },
  {
    id: 'trivandrum_shanghumugham_beach',
    name: 'Shanghumugham Beach',
    description: 'A popular city beach near the airport, famous for its giant mermaid sculpture and beautiful sunsets.',
    location: 'Trivandrum',
    imageId: 'attraction-shanghumugham-beach',
    district: 'Trivandrum',
    hasDetails: true,
  },
  {
    id: 'trivandrum_napier_museum',
    name: 'Napier Museum',
    description: "A 19th-century Indo-Saracenic museum housing a rich collection of Kerala's artistic and cultural heritage.",
    location: 'Trivandrum',
    imageId: 'attraction-napier-museum',
    district: 'Trivandrum',
    hasDetails: true,
  },
  {
    id: 'trivandrum_zoo',
    name: 'Thiruvananthapuram Zoo',
    description: 'One of the oldest zoos in India, set in a lush botanical garden with a wide variety of animals and birds.',
    location: 'Trivandrum',
    imageId: 'attraction-trivandrum-zoo',
    district: 'Trivandrum',
    hasDetails: true,
  },
  {
    id: 'trivandrum_poovar_island',
    name: 'Poovar Island',
    description: 'A serene estuary where the river, lake, and sea meet, famous for its mangrove forests and floating resorts.',
    location: 'Trivandrum',
    imageId: 'attraction-poovar-island',
    district: 'Trivandrum',
    hasDetails: true,
  },
  {
    id: 'trivandrum_kanakakunnu_palace',
    name: 'Kanakakunnu Palace',
    description: 'A beautiful heritage palace in the heart of the city, known for hosting various cultural events and festivals.',
    location: 'Trivandrum',
    imageId: 'attraction-kanakakunnu-palace',
    district: 'Trivandrum',
    hasDetails: true,
  },
  {
    id: 'wayanad_banasura_sagar_dam',
    lat: 11.6687,
    lng: 75.9547,
    name: 'Banasura Sagar Dam',
    description: 'India’s largest earth dam, offering speed boating, trekking, and stunning views of the surrounding hills.',
    location: 'Wayanad',
    imageId: 'attraction-banasura-dam',
    district: 'Wayanad',
    hasDetails: true,
  },
  {
    id: 'wayanad_edakkal_caves',
    lat: 11.6258,
    lng: 76.2356,
    name: 'Edakkal Caves',
    description: 'Prehistoric caves in Wayanad with fascinating rock engravings that date back thousands of years.',
    location: 'Wayanad',
    imageId: 'attraction-edakkal-caves',
    district: 'Wayanad',
    hasDetails: true,
  },
  {
    id: 'wayanad_chembra_peak',
    lat: 11.5122,
    lng: 76.0894,
    name: 'Chembra Peak',
    description: 'A trekking paradise in Wayanad, famous for its scenic beauty and a heart-shaped lake on the way to the peak.',
    location: 'Wayanad',
    imageId: 'attraction-chembra-peak',
    district: 'Wayanad',
    hasDetails: true,
  },
  {
    id: 'wayanad_soochipara_waterfalls',
    lat: 11.5122,
    lng: 76.1631,
    name: 'Soochipara Waterfalls',
    description: 'A three-tiered waterfall surrounded by dense forest, popular for swimming and nature trekking.',
    location: 'Wayanad',
    imageId: 'attraction-soochipara-falls',
    district: 'Wayanad',
    hasDetails: true,
  },
  {
    id: 'wayanad_pookode_lake',
    name: 'Pookode Lake',
    description: 'A natural freshwater lake surrounded by forests, known for its scenic paths and boating.',
    location: 'Wayanad',
    imageId: 'attraction-pookode-lake',
    district: 'Wayanad',
    hasDetails: true,
  },
  {
    id: 'wayanad_kuruvadweep_island',
    name: 'Kuruvadweep Island',
    description: 'A protected river delta on the Kabini River known for bamboo rafting, dense forest, and rich biodiversity.',
    location: 'Wayanad',
    imageId: 'attraction-kuruvadweep-island',
    district: 'Wayanad',
    hasDetails: true,
  },
  {
    id: 'wayanad_karapuzha_dam',
    name: 'Karapuzha Dam',
    description: "A major tourism hotspot with an adventure park, boating, and gardens around one of India's largest earth dams.",
    location: 'Wayanad',
    imageId: 'attraction-karapuzha-dam',
    district: 'Wayanad',
    hasDetails: true,
  },
  {
    id: 'wayanad_meenmutty_waterfalls',
    name: 'Meenmutty Waterfalls',
    description: 'A powerful three-tiered waterfall, one of the largest in Wayanad, requiring a scenic forest trek to reach.',
    location: 'Wayanad',
    imageId: 'attraction-meenmutty-falls',
    district: 'Wayanad',
    hasDetails: true,
  },
  {
    id: 'wayanad_kanthanpara_waterfalls',
    name: 'Kanthanpara Waterfalls',
    description: 'A beautiful and easily accessible waterfall in Wayanad, perfect for families and a peaceful nature experience.',
    location: 'Wayanad',
    imageId: 'attraction-kanthanpara-falls',
    district: 'Wayanad',
    hasDetails: true,
  },
  {
    id: 'wayanad_tholpetty_wildlife_sanctuary',
    name: 'Tholpetty Wildlife Sanctuary',
    description: 'A major wildlife zone known for jeep safaris, rich wildlife, and part of the Nilgiri Biosphere Reserve.',
    location: 'Wayanad',
    imageId: 'attraction-tholpetty-safari',
    district: 'Wayanad',
    hasDetails: true,
  },
  {
    id: 'wayanad_muthanga_wildlife_sanctuary',
    name: 'Muthanga Wildlife Sanctuary',
    description: 'Part of the Nilgiri Biosphere Reserve, offering jeep safaris to spot elephants, tigers, and deer.',
    location: 'Wayanad',
    imageId: 'attraction-muthanga-safari',
    district: 'Wayanad',
    hasDetails: true,
  },
  {
    id: 'alleppey_backwaters_houseboats',
    lat: 9.4981,
    lng: 76.3388,
    name: 'Alleppey Backwaters & Houseboats',
    description: 'Iconic backwaters famous for traditional kettuvallam houseboats cruising through canals and lakes.',
    location: 'Alappuzha',
    imageId: 'attraction-alleppey-backwaters',
    district: 'Alappuzha',
    hasDetails: true,
  },
  {
    id: 'alleppey_alappuzha_beach',
    name: 'Alappuzha Beach',
    description: 'A historic coastal landmark known for its long sandy shore, ancient sea bridge, and cultural festivals.',
    location: 'Alappuzha',
    imageId: 'attraction-alappuzha-beach',
    district: 'Alappuzha',
    hasDetails: true,
  },
  {
    id: 'alleppey_alappuzha_lighthouse',
    name: 'Alappuzha Lighthouse',
    description: 'A historic 19th-century lighthouse offering panoramic views of the Arabian Sea and Alappuzha town.',
    location: 'Alappuzha',
    imageId: 'attraction-alappuzha-lighthouse',
    district: 'Alappuzha',
    hasDetails: true,
  },
  {
    id: 'alleppey_ambalappuzha_sree_krishna_temple',
    name: 'Ambalappuzha Sree Krishna Temple',
    description: 'Historic Krishna temple in Kerala famed for its delicious Pal Payasam (milk pudding) offering.',
    location: 'Alappuzha',
    imageId: 'attraction-ambalappuzha-temple',
    district: 'Alappuzha',
    hasDetails: true,
  },
  {
    id: 'alleppey_krishnapuram_palace',
    name: 'Krishnapuram Palace',
    description: "A historic palace-turned-museum known for its traditional Kerala architecture and the famous 'Gajendra Moksham' mural.",
    location: 'Kayamkulam',
    imageId: 'attraction-krishnapuram-palace',
    district: 'Alappuzha',
    hasDetails: true,
  },
  {
    id: 'alleppey_pathiramanal_island',
    name: 'Pathiramanal Island',
    description: 'A scenic island in Vembanad Lake known for its rich birdlife and serene natural beauty.',
    location: 'Muhamma',
    imageId: 'attraction-pathiramanal-island',
    district: 'Alappuzha',
    hasDetails: true,
  },
  {
    id: 'alleppey_kuttanad_backwaters_paddy_fields',
    name: 'Kuttanad Backwaters & Paddy Fields',
    description: 'Known as the ‘Rice Bowl of Kerala’, Kuttanad is famous for its below-sea-level paddy cultivation and scenic backwater canals.',
    location: 'Kuttanad',
    imageId: 'attraction-kuttanad-paddy-fields',
    district: 'Alappuzha',
    hasDetails: true,
  },
  {
    id: 'alleppey_champakulam_st_marys_forane_church',
    name: 'St. Mary’s Forane Church, Champakulam',
    description: 'One of the oldest Christian churches in India, with beautiful architecture, located in the scenic Kuttanad backwaters.',
    location: 'Champakulam',
    imageId: 'attraction-champakulam-church',
    district: 'Alappuzha',
    hasDetails: true,
  },
  {
    id: 'kozhikode_kappad_beach',
    name: 'Kappad Beach',
    description: 'Historic beach where Vasco da Gama first landed in India in 1498. Features golden sands, rocky formations, and a commemorative monument.',
    location: 'Kappad',
    imageId: 'attraction-kappad-beach',
    district: 'Kozhikode',
    hasDetails: true,
  },
  {
    id: 'kannur_muzhappilangad_drive_in_beach',
    lat: 11.7932,
    lng: 75.4441,
    name: 'Muzhappilangad Drive-in Beach',
    description: "India's longest drive-in beach with 4 km of hard-packed sand, perfect for driving, sunset views, and beach activities.",
    location: 'Muzhappilangad',
    imageId: 'attraction-muzhappilangad-beach',
    district: 'Kannur',
    hasDetails: true,
  },
  {
    id: 'kannur_st_angelos_fort',
    name: "St. Angelo's Fort",
    description: 'A 16th-century Portuguese fort built in 1505, featuring triangular bastions, laterite walls, and panoramic Arabian Sea views.',
    location: 'Kannur',
    imageId: 'attraction-st-angelos-fort',
    district: 'Kannur',
    hasDetails: true,
  },
  {
    id: 'kannur_payyambalam_beach',
    name: 'Payyambalam Beach',
    description: "Kannur's most popular urban beach with clean shores, landscaped gardens, and stunning sunset views.",
    location: 'Kannur',
    imageId: 'attraction-payyambalam-beach',
    district: 'Kannur',
    hasDetails: true,
  },
  {
    id: 'kannur_arakkal_museum',
    name: 'Arakkal Museum',
    description: "Museum showcasing Kerala's only Muslim royal family legacy, with artifacts, documents, and traditional palace architecture.",
    location: 'Kannur',
    imageId: 'attraction-arakkal-museum',
    district: 'Kannur',
    hasDetails: true,
  },
  {
    id: 'kannur_parassinikadavu_muthappan_temple',
    lat: 11.9825,
    lng: 75.4020,
    name: 'Parassinikadavu Muthappan Temple',
    description: 'Unique temple where Theyyam is performed daily as worship, featuring inclusive rituals and cultural traditions.',
    location: 'Parassinikadavu',
    imageId: 'attraction-muthappan-temple',
    district: 'Kannur',
    hasDetails: true,
  },
  {
    id: 'kannur_paithalmala_hill_station',
    name: 'Paithalmala Hill Station',
    description: 'Scenic hill station at 1,370m altitude with rolling meadows, fog-covered peaks, and trekking trails through Western Ghats.',
    location: 'Kappimala',
    imageId: 'attraction-paithalmala',
    district: 'Kannur',
    hasDetails: true,
  },
  {
    id: 'kannur_madayipara',
    name: 'Madayipara',
    description: 'Biodiversity hotspot hilltop plateau famous for seasonal flower blooms, ancient fort ruins, and 360° panoramic views.',
    location: 'Pazhayangadi',
    imageId: 'attraction-madayipara',
    district: 'Kannur',
    hasDetails: true,
  },
  {
    id: 'kannur_dharmadom_island',
    name: 'Dharmadom Island',
    description: 'Small green island accessible on foot during low tide, featuring lush coconut groves and rocky shores.',
    location: 'Dharmadom',
    imageId: 'attraction-dharmadom-island',
    district: 'Kannur',
    hasDetails: true,
  },
  {
    id: 'kannur_thalassery_fort',
    name: 'Thalassery Fort',
    description: 'British fort built in 1708 with massive laterite walls, underground chambers, and historic significance in spice trade.',
    location: 'Thalassery',
    imageId: 'attraction-thalassery-fort',
    district: 'Kannur',
    hasDetails: true,
  },
  {
    id: 'kannur_lighthouse',
    name: 'Kannur Lighthouse',
    description: "Kerala's first lighthouse built in 1903, offering panoramic coastal views and a maritime heritage museum.",
    location: 'Kannur',
    imageId: 'attraction-kannur-lighthouse',
    district: 'Kannur',
    hasDetails: true,
  },
  {
    id: 'kozhikode_beach',
    lat: 11.2561,
    lng: 75.7694,
    name: 'Kozhikode Beach',
    description: 'Historic coastal hub once a major spice trade port, now a popular sunset beach with promenade, food stalls, and old pier remains.',
    location: 'Kozhikode',
    imageId: 'attraction-kozhikode-beach',
    district: 'Kozhikode',
    hasDetails: true,
  },
  {
    id: 'kozhikode_beypore_beach_port',
    name: 'Beypore Beach & Port',
    description: 'Ancient port town renowned for traditional wooden Uru shipbuilding and the scenic 2km Pulimuttu stone pier extending into the sea.',
    location: 'Beypore',
    imageId: 'attraction-beypore-beach',
    district: 'Kozhikode',
    hasDetails: true,
  },
  {
    id: 'kozhikode_thusharagiri_waterfalls',
    lat: 11.4722,
    lng: 76.0536,
    name: 'Thusharagiri Waterfalls',
    description: 'Western Ghats eco-tourism destination with multiple waterfalls, trekking routes, and lush forest trails along Chalippuzha River.',
    location: 'Kodenchery',
    imageId: 'attraction-thusharagiri-waterfalls',
    district: 'Kozhikode',
    hasDetails: true,
  },
  {
    id: 'kozhikode_sm_street',
    name: 'SM Street (Sweet Meat Street)',
    description: "Kozhikode's oldest commercial street famous for colorful halwa, traditional sweets, textiles, and bustling market atmosphere.",
    location: 'Kozhikode',
    imageId: 'attraction-sm-street',
    district: 'Kozhikode',
    hasDetails: true,
  },
  {
    id: 'kozhikode_mananchira_square',
    name: 'Mananchira Square',
    description: "Historical tank and park in city center, once the Zamorins' private bathing tank, now a landscaped public space with cultural events.",
    location: 'Kozhikode',
    imageId: 'attraction-mananchira-square',
    district: 'Kozhikode',
    hasDetails: true,
  },
  {
    id: 'kozhikode_kadalundi_bird_sanctuary',
    name: 'Kadalundi Bird Sanctuary',
    description: 'Scenic estuary bird sanctuary with mangroves and sandbanks, home to migratory and resident coastal birds, ideal for birdwatching.',
    location: 'Kadalundi',
    imageId: 'attraction-kadalundi-bird-sanctuary',
    district: 'Kozhikode',
    hasDetails: true,
  },
  {
    id: 'kozhikode_vayalada_viewpoint',
    name: 'Vayalada Viewpoint',
    description: "Hilltop viewpoint called 'Gavi of Malabar' offering cloud-filled valley views, misty mornings, and peaceful Western Ghats scenery.",
    location: 'Vayalada',
    imageId: 'attraction-vayalada-viewpoint',
    district: 'Kozhikode',
    hasDetails: true,
  },
  {
    id: 'kozhikode_pazhassi_raja_museum',
    name: 'Pazhassi Raja Museum & Art Gallery',
    description: "State museum showcasing Kerala's history, ancient artifacts, Raja Ravi Varma paintings, and exhibits on freedom fighter Pazhassi Raja.",
    location: 'Kozhikode',
    imageId: 'attraction-pazhassi-raja-museum',
    district: 'Kozhikode',
    hasDetails: true,
  },
  {
    id: 'kasargod_bekal_fort_beach',
    lat: 12.3887,
    lng: 75.0262,
    name: 'Bekal Fort & Bekal Beach',
    description: "One of Kerala's largest sea forts with keyhole shape, offering panoramic coastal views and adjoining beach.",
    location: 'Bekal',
    imageId: 'attraction-bekal-fort',
    district: 'Kasargod',
    hasDetails: true,
  },
  {
    id: 'kasargod_valiyaparamba_backwaters',
    name: 'Valiyaparamba Backwaters',
    description: 'Serene backwater stretch with small islands, less crowded than Alleppey, ideal for peaceful houseboat cruises.',
    location: 'Nileshwaram',
    imageId: 'attraction-valiyaparamba-backwaters',
    district: 'Kasargod',
    hasDetails: true,
  },
  {
    id: 'kasargod_ranipuram_hill_station',
    name: 'Ranipuram Hill Station',
    description: 'Cool hill station with meadows and shola forests at 750-1000m altitude, popular for trekking in Western Ghats.',
    location: 'Ranipuram',
    imageId: 'attraction-ranipuram',
    district: 'Kasargod',
    hasDetails: true,
  },
  {
    id: 'kasargod_chandragiri_fort',
    name: 'Chandragiri Fort & River Viewpoint',
    description: 'Hilltop fort ruins offering beautiful sunset views over Chandragiri River and backwaters.',
    location: 'Chandragiri',
    imageId: 'attraction-chandragiri-fort',
    district: 'Kasargod',
    hasDetails: true,
  },
  {
    id: 'kasargod_hosdurg_fort_nityanand_ashram',
    name: 'Hosdurg Fort & Nityanand Ashram Caves',
    description: 'Historic fort combined with spiritual ashram caves, blending heritage and meditation spaces near Kanhangad.',
    location: 'Kanhangad',
    imageId: 'attraction-hosdurg-fort',
    district: 'Kasargod',
    hasDetails: true,
  },
  {
    id: 'kasargod_kappil_beach',
    name: 'Kappil Beach',
    description: 'Quiet scenic beach near Bekal with backwaters on one side and sea on the other, perfect for peaceful walks.',
    location: 'Kappil',
    imageId: 'attraction-kappil-beach',
    district: 'Kasargod',
    hasDetails: true,
  },
  {
    id: 'kasargod_madhur_temple',
    name: 'Madhur Temple',
    description: 'Prominent riverside temple with multilayered gopurams dedicated to Lord Shiva and Lord Ganesha.',
    location: 'Madhur',
    imageId: 'attraction-madhur-temple',
    district: 'Kasargod',
    hasDetails: true,
  },
  {
    id: 'kasargod_ananthapura_lake_temple',
    name: 'Ananthapura Lake Temple',
    description: 'Unique temple in the center of a lake, considered the original seat of Anantha Padmanabha deity.',
    location: 'Ananthapura',
    imageId: 'attraction-ananthapura-temple',
    district: 'Kasargod',
    hasDetails: true,
  },
  {
    id: 'kasargod_malik_dinar_mosque',
    name: 'Malik Dinar Mosque',
    description: 'One of the oldest mosques in India, associated with early arrival of Islam on the Malabar Coast.',
    location: 'Thalangara',
    imageId: 'attraction-malik-dinar-mosque',
    district: 'Kasargod',
    hasDetails: true,
  },
  {
    id: 'kasargod_nileshwaram_backwaters_town',
    name: 'Nileshwaram Backwaters & Heritage Town',
    description: 'Historic town with backwaters, old palaces, temples, and strong Theyyam cultural traditions.',
    location: 'Nileshwaram',
    imageId: 'attraction-nileshwaram',
    district: 'Kasargod',
    hasDetails: true,
  },
  {
    id: 'kochi_fort_kochi',
    lat: 9.9678,
    lng: 76.2420,
    name: 'Fort Kochi & Chinese Fishing Nets',
    description: 'Historic port-town with colonial streets, churches, and iconic Chinese fishing nets along the Arabian Sea.',
    location: 'Fort Kochi',
    imageId: 'attraction-fort-kochi',
    district: 'Ernakulam',
    hasDetails: true,
  },
  {
    id: 'kochi_mattancherry_palace_jew_town',
    lat: 9.9582,
    lng: 76.2593,
    name: 'Mattancherry Palace & Jew Town',
    description: 'Dutch Palace museum with royal murals, adjacent to historic Jew Town with antique shops and Paradesi Synagogue.',
    location: 'Mattancherry',
    imageId: 'attraction-mattancherry-palace',
    district: 'Ernakulam',
    hasDetails: true,
  },
  {
    id: 'kochi_marine_drive',
    name: 'Marine Drive',
    description: 'Popular waterfront promenade overlooking Kochi backwaters, perfect for evening walks and boat cruises.',
    location: 'Ernakulam',
    imageId: 'attraction-marine-drive',
    district: 'Ernakulam',
    hasDetails: true,
  },
  {
    id: 'kochi_cherai_beach',
    name: 'Cherai Beach',
    description: 'Long sandy beach on Vypin Island with unique sea-backwater landscape, ideal for family outings and swimming.',
    location: 'Cherai',
    imageId: 'attraction-cherai-beach',
    district: 'Ernakulam',
    hasDetails: true,
  },
  {
    id: 'kochi_hill_palace_museum',
    name: 'Hill Palace Museum',
    description: "Kerala's largest archaeological museum in former Cochin royal residence, featuring crown jewels and artifacts.",
    location: 'Tripunithura',
    imageId: 'attraction-hill-palace',
    district: 'Ernakulam',
    hasDetails: true,
  },
  {
    id: 'kochi_mangalavanam_bird_sanctuary',
    name: 'Mangalavanam Bird Sanctuary',
    description: "Urban mangrove bird sanctuary in city center, known as Kochi's 'green lung' with resident and migratory birds.",
    location: 'Kochi',
    imageId: 'attraction-mangalavanam',
    district: 'Ernakulam',
    hasDetails: true,
  },
  {
    id: 'thrissur_vadakkunnathan_temple',
    name: 'Vadakkunnathan Temple',
    description: 'Ancient Shiva temple at heart of Thrissur, known for Kerala architecture and famous Thrissur Pooram festival.',
    location: 'Thrissur',
    imageId: 'attraction-vadakkunnathan-temple',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'thrissur_zoo_state_museum',
    name: 'Thrissur Zoo & State Museum',
    description: "One of Kerala's oldest zoos with animal enclosures and cultural exhibits, popular family attraction.",
    location: 'Thrissur',
    imageId: 'attraction-thrissur-zoo',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'thrissur_sakthan_thampuran_palace',
    name: 'Sakthan Thampuran Palace',
    description: 'Historic palace-museum with Kerala-Dutch architecture, showcasing royal artifacts and Thrissur history.',
    location: 'Thrissur',
    imageId: 'attraction-sakthan-palace',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'thrissur_our_lady_of_dolours_basilica',
    name: 'Our Lady of Dolours Basilica',
    description: 'One of the largest churches in India with grand Gothic-style architecture and three towering spires.',
    location: 'Thrissur',
    imageId: 'attraction-dolours-basilica',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'thrissur_athirappilly_waterfalls',
    lat: 10.2847,
    lng: 76.5686,
    name: 'Athirappilly Waterfalls',
    description: "Often called 'Niagara of India', Kerala's most famous and largest waterfall with spectacular views.",
    location: 'Athirappilly',
    imageId: 'attraction-athirappilly',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'thrissur_vazhachal_waterfalls',
    name: 'Vazhachal Waterfalls',
    description: 'Scenic river rapids and cascades on Chalakudy River, surrounded by lush forest near Athirappilly.',
    location: 'Vazhachal',
    imageId: 'attraction-vazhachal',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'thrissur_chavakkad_beach',
    name: 'Chavakkad Beach',
    description: 'Quiet beach near Guruvayur with scenic estuary where river meets sea, popular with pilgrims.',
    location: 'Chavakkad',
    imageId: 'attraction-chavakkad-beach',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'thrissur_snehatheeram_beach',
    name: 'Snehatheeram Beach',
    description: "Well-maintained beach with park facilities and children's play area, ideal for family outings.",
    location: 'Thalikulam',
    imageId: 'attraction-snehatheeram-beach',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'thrissur_guruvayur_temple',
    lat: 10.5946,
    lng: 76.0394,
    name: 'Guruvayur Sree Krishna Temple',
    description: "One of South India's most important Krishna temples, called 'Dwaraka of the South', major pilgrimage center.",
    location: 'Guruvayur',
    imageId: 'attraction-guruvayur-temple',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'thrissur_punnathur_kotta_elephant_sanctuary',
    name: 'Punnathur Kotta Elephant Sanctuary',
    description: 'Former palace compound housing temple elephants of Guruvayur, unique cultural attraction.',
    location: 'Punnathur',
    imageId: 'attraction-punnathur-kotta',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'thrissur_chettuva_backwaters',
    name: 'Chettuva Backwaters',
    description: 'Scenic backwater area with mangroves and boat rides, quieter alternative near Guruvayur region.',
    location: 'Chettuva',
    imageId: 'attraction-chettuva-backwaters',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'thrissur_kerala_kalamandalam',
    name: 'Kerala Kalamandalam',
    description: 'Premier center for learning classical performing arts including Kathakali, Mohiniyattam, and percussion.',
    location: 'Cheruthuruthy',
    imageId: 'attraction-kalamandalam',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'thrissur_peechi_dam_wildlife_sanctuary',
    name: 'Peechi Dam & Wildlife Sanctuary',
    description: 'Scenic dam and reservoir with adjoining wildlife sanctuary, popular picnic spot east of Thrissur.',
    location: 'Peechi',
    imageId: 'attraction-peechi-dam',
    district: 'Thrissur',
    hasDetails: true,
  },
  {
    id: 'idukki_arch_dam',
    name: 'Idukki Arch Dam & Hill View Park',
    description: "Asia's first arch dam, an engineering marvel with spectacular reservoir views and Hill View Park.",
    location: 'Idukki',
    imageId: 'attraction-idukki-dam',
    district: 'Idukki',
    hasDetails: true,
  },
  {
    id: 'idukki_munnar_hill_station',
    lat: 10.0892,
    lng: 77.0597,
    name: 'Munnar Hill Station & Tea Estates',
    description: "One of India's most famous hill stations with rolling tea estates, cool climate, and mist-covered hills.",
    location: 'Munnar',
    imageId: 'attraction-munnar',
    district: 'Idukki',
    hasDetails: true,
  },
  {
    id: 'idukki_eravikulam_national_park',
    name: 'Eravikulam National Park',
    description: 'High-altitude national park famous for endangered Nilgiri tahr and rolling grasslands near Munnar.',
    location: 'Near Munnar',
    imageId: 'attraction-eravikulam',
    district: 'Idukki',
    hasDetails: true,
  },
  {
    id: 'idukki_thekkady_periyar_tiger_reserve',
    lat: 9.6063,
    lng: 77.1697,
    name: 'Thekkady & Periyar Tiger Reserve',
    description: 'Famous wildlife reserve with boat safaris on Periyar Lake, home to elephants, tigers, and diverse fauna.',
    location: 'Thekkady',
    imageId: 'attraction-periyar',
    district: 'Idukki',
    hasDetails: true,
  },
  {
    id: 'idukki_ramakkalmedu',
    name: 'Ramakkalmedu Viewpoint',
    description: 'Windy hilltop with stunning views over Tamil Nadu plains, marked by giant Kuravan-Kurathi statues.',
    location: 'Ramakkalmedu',
    imageId: 'attraction-ramakkalmedu',
    district: 'Idukki',
    hasDetails: true,
  },
  {
    id: 'idukki_vagamon_hill_station',
    lat: 9.6862,
    lng: 76.9052,
    name: 'Vagamon Meadows & Hills',
    description: 'Cool highland with grass-covered hills, pine forests, and valleys, popular for paragliding and nature stays.',
    location: 'Vagamon',
    imageId: 'attraction-vagamon',
    district: 'Idukki',
    hasDetails: true,
  },
  {
    id: 'idukki_kalvari_mount',
    name: 'Kalvari Mount',
    description: 'Hilltop viewpoint and pilgrimage site with sweeping views of Idukki reservoir and surrounding mountains.',
    location: 'Near Idukki',
    imageId: 'attraction-kalvari-mount',
    district: 'Idukki',
    hasDetails: true,
  },
  {
    id: 'idukki_anchuruli_tunnel',
    name: 'Anchuruli Tunnel & Lake Viewpoint',
    description: 'Scenic lakeside viewpoint known for dramatic water tunnel outlet into Idukki reservoir.',
    location: 'Anchuruli',
    imageId: 'attraction-anchuruli',
    district: 'Idukki',
    hasDetails: true,
  },
  {
    id: 'kottayam_kumarakom_backwaters',
    lat: 9.6175,
    lng: 76.4301,
    name: 'Kumarakom Backwaters',
    description: 'Serene backwater village on Vembanad Lake, known for houseboat cruises and luxury resorts.',
    location: 'Kumarakom',
    imageId: 'attraction-kumarakom-backwaters',
    district: 'Kottayam',
    hasDetails: true,
  },
  {
    id: 'kottayam_kumarakom_bird_sanctuary',
    name: 'Kumarakom Bird Sanctuary',
    description: 'Protected wetland ecosystem famous for migratory birds and scenic nature trails.',
    location: 'Kumarakom',
    imageId: 'attraction-kumarakom-bird-sanctuary',
    district: 'Kottayam',
    hasDetails: true,
  },
  {
    id: 'kottayam_illikkal_kallu',
    name: 'Illikkal Kallu',
    description: 'Dramatic hilltop viewpoint with a massive rock pillar and panoramic valley views.',
    location: 'Moonnilavu',
    imageId: 'attraction-illikkal-kallu',
    district: 'Kottayam',
    hasDetails: true,
  },
  {
    id: 'kottayam_thazhathangady_juma_masjid',
    name: 'Thazhathangady Juma Masjid',
    description: 'One of Kerala’s oldest mosques, renowned for intricate wooden carvings and architecture.',
    location: 'Thazhathangady',
    imageId: 'attraction-thazhathangady-masjid',
    district: 'Kottayam',
    hasDetails: true,
  },
  {
    id: 'kottayam_aruvikkuzhy_waterfalls',
    name: 'Aruvikkuzhy Waterfalls',
    description: 'Lush, family-friendly waterfall surrounded by rubber plantations, ideal for picnics.',
    location: 'Pallickathode',
    imageId: 'attraction-aruvikkuzhy-waterfalls',
    district: 'Kottayam',
    hasDetails: true,
  },
  {
    id: 'kottayam_cheriapally_church',
    name: 'St. Mary’s Church Cheriapally',
    description: 'Historic church built in 1579, famous for Persian-Christian history and ancient murals.',
    location: 'Kottayam',
    imageId: 'attraction-cheriapally-church',
    district: 'Kottayam',
    hasDetails: true,
  },
  {
    id: 'kottayam_bharananganam_st_alphonsa',
    name: 'St. Alphonsa Pilgrimage Centre',
    description: 'Major pilgrimage centre housing the tomb of St. Alphonsa, India’s first woman saint.',
    location: 'Bharananganam',
    imageId: 'attraction-st-alphonsa',
    district: 'Kottayam',
    hasDetails: true,
  },
  {
    id: 'kottayam_mannanam_st_chavara',
    name: 'St. Joseph’s Church & Chavara Centre',
    description: 'Heritage centre with St. Chavara’s tomb and the first Malayalam printing press.',
    location: 'Mannanam',
    imageId: 'attraction-mannanam-chavara',
    district: 'Kottayam',
    hasDetails: true,
  },
  {
    id: 'kollam_ashtamudi_lake',
    name: 'Ashtamudi Lake',
    description: 'Serene backwater lake known as the gateway to Kerala’s backwaters, famous for houseboat cruises.',
    location: 'Kollam',
    imageId: 'attraction-ashtamudi-lake',
    district: 'Kollam',
    hasDetails: true,
  },
  {
    id: 'kollam_jatayu_earths_center',
    name: 'Jatayu Earth’s Center',
    description: 'Adventure park featuring the world’s largest bird sculpture, cable cars, and rock activities.',
    location: 'Chadayamangalam',
    imageId: 'attraction-jatayu-earths-center',
    district: 'Kollam',
    hasDetails: true,
  },
  {
    id: 'kollam_palaruvi_waterfalls',
    name: 'Palaruvi Waterfalls',
    description: 'One of Kerala’s highest waterfalls, cascading down 300 feet amidst dense forests.',
    location: 'Aryankavu',
    imageId: 'attraction-palaruvi-waterfalls',
    district: 'Kollam',
    hasDetails: true,
  },
  {
    id: 'kollam_thenmala_ecotourism',
    name: 'Thenmala Eco-Tourism',
    description: 'India’s first planned eco-tourism destination with boating, trekking, and musical fountains.',
    location: 'Thenmala',
    imageId: 'attraction-thenmala-ecotourism',
    district: 'Kollam',
    hasDetails: true,
  },
  {
    id: 'kollam_sasthamkotta_lake',
    name: 'Sasthamkotta Lake',
    description: 'The largest freshwater lake in Kerala, known for its scenic beauty and ancient Sastha temple.',
    location: 'Sasthamkotta',
    imageId: 'attraction-sasthamkotta-lake',
    district: 'Kollam',
    hasDetails: true,
  },
  {
    id: 'kollam_kollam_beach',
    name: 'Kollam Beach',
    description: 'Popular beach with a historic lighthouse, park, and stunning sunset views.',
    location: 'Kollam',
    imageId: 'attraction-kollam-beach',
    district: 'Kollam',
    hasDetails: true,
  },
  {
    id: 'kollam_thangassery_lighthouse',
    name: 'Thangassery Lighthouse',
    description: 'Historic lighthouse built in 1902 offering panoramic views of the Arabian Sea and coastline.',
    location: 'Thangassery',
    imageId: 'attraction-thangassery-lighthouse',
    district: 'Kollam',
    hasDetails: true,
  },
  {
    id: 'kollam_munroe_island',
    name: 'Munroe Island',
    description: 'Hidden gem of backwaters offering canoe rides through narrow canals and mangrove forests.',
    location: 'Munroe Thuruthu',
    imageId: 'attraction-munroe-island',
    district: 'Kollam',
    hasDetails: true,
  },
  {
    id: 'kollam_thevally_palace',
    name: 'Thevally Palace',
    description: 'Heritage palace on the banks of Ashtamudi Lake, showcasing a blend of colonial and Kerala architecture.',
    location: 'Thevally',
    imageId: 'attraction-thevally-palace',
    district: 'Kollam',
    hasDetails: true,
  },
  {
    id: 'kollam_asramam_adventure_park',
    name: 'Asramam Adventure Park',
    description: 'Urban park by the lake with boating facilities, mangroves, and picnic spots.',
    location: 'Asramam',
    imageId: 'attraction-asramam-adventure-park',
    district: 'Kollam',
    hasDetails: true,
  },
  {
    id: 'palakkad_parambikulam_tiger_reserve',
    name: 'Parambikulam Tiger Reserve',
    description: 'A protected tiger reserve known for pristine forests, tribal eco-tourism, and rich wildlife.',
    location: 'Anamalai Range',
    imageId: 'attraction-parambikulam-tiger-reserve',
    district: 'Palakkad',
    hasDetails: true,
  },
  {
    id: 'palakkad_silent_valley_national_park',
    name: 'Silent Valley National Park',
    description: 'A pristine tropical rainforest famous for its untouched ecosystem and rare species like the Lion-tailed Macaque.',
    location: 'Mukkali',
    imageId: 'attraction-silent-valley-national-park',
    district: 'Palakkad',
    hasDetails: true,
  },
  {
    id: 'palakkad_malampuzha_dam_and_gardens',
    name: 'Malampuzha Dam & Gardens',
    description: 'A famous dam and garden complex built in 1955, known for boating, ropeway rides, and landscaped gardens.',
    location: 'Malampuzha',
    imageId: 'attraction-malampuzha-dam-and-gardens',
    district: 'Palakkad',
    hasDetails: true,
  },
  {
    id: 'palakkad_palakkad_fort',
    name: 'Palakkad Fort (Tipu\'s Fort)',
    description: 'A well-preserved 18th-century fort built by Hyder Ali and associated with Tipu Sultan\'s era.',
    location: 'Palakkad Town',
    imageId: 'attraction-palakkad-fort',
    district: 'Palakkad',
    hasDetails: true,
  },
  {
    id: 'palakkad_nelliyampathy_hills',
    name: 'Nelliyampathy Hills',
    description: 'A scenic hill station known for plantations, viewpoints, and cool misty weather.',
    location: 'Nenmara',
    imageId: 'attraction-nelliyampathy-hills',
    district: 'Palakkad',
    hasDetails: true,
  },
  {
    id: 'palakkad_dhoni_waterfalls',
    name: 'Dhoni Waterfalls',
    description: 'A scenic forest waterfall accessible only through a guided 4 km trek.',
    location: 'Dhoni',
    imageId: 'attraction-dhoni-waterfalls',
    district: 'Palakkad',
    hasDetails: true,
  },
  {
    id: 'palakkad_seethargundu_viewpoint',
    name: 'Seethargundu Viewpoint',
    description: 'A breathtaking cliffside viewpoint offering panoramic views of the Palakkad plains and surrounding forest valleys.',
    location: 'Nelliyampathy',
    imageId: 'attraction-seethargundu-viewpoint',
    district: 'Palakkad',
    hasDetails: true,
  },
  {
    id: 'palakkad_meenvallam_waterfalls',
    name: 'Meenvallam Waterfalls',
    description: 'A picturesque multi-step waterfall popular with locals and visitors for its clean pools and serene setting.',
    location: 'Meenvallam',
    imageId: 'attraction-meenvallam-waterfalls',
    district: 'Palakkad',
    hasDetails: true,
  },
  {
    id: 'palakkad_siruvani_dam_and_waterfalls',
    name: 'Siruvani Dam & Waterfalls',
    description: 'A scenic dam and waterfall known for having one of the sweetest waters in India, surrounded by Western Ghats forest.',
    location: 'Siruvani Hills',
    imageId: 'attraction-siruvani-dam-and-waterfalls',
    district: 'Palakkad',
    hasDetails: true,
  },
  {
    id: 'palakkad_jain_temple_jainmedu',
    name: 'Jain Temple (Jainmedu)',
    description: 'A 15th-century Jain temple built by Jain merchants, known for its unique Kerala-Jain architectural style.',
    location: 'Jainmedu',
    imageId: 'attraction-jain-temple-jainmedu',
    district: 'Palakkad',
    hasDetails: true,
  },
  {
    id: 'idukki_munnar_eravikulam_national_park',
    name: 'Eravikulam National Park (Rajamalai)',
    description: 'Home to the endangered Nilgiri Tahr and famous for the Neelakurinji blooms.',
    location: 'Munnar',
    imageId: 'attraction-eravikulam-national-park',
    district: 'Munnar',
    hasDetails: true,
  },
  {
    id: 'idukki_munnar_top_station',
    name: 'Top Station',
    description: 'Historic highest point offering panoramic views of the Western Ghats and Tamil Nadu valley.',
    location: 'Munnar',
    imageId: 'attraction-top-station',
    district: 'Munnar',
    hasDetails: true,
  },
  {
    id: 'idukki_munnar_mattupetty_dam',
    name: 'Mattupetty Dam & Lake',
    description: 'Popular for speed boating and scenic views, surrounded by Shola forests.',
    location: 'Munnar',
    imageId: 'attraction-mattupetty-dam',
    district: 'Munnar',
    hasDetails: true,
  },
  {
    id: 'idukki_munnar_echo_point',
    name: 'Echo Point',
    description: 'Scenic spot known for its natural echo phenomenon and beautiful lake views.',
    location: 'Munnar',
    imageId: 'attraction-echo-point',
    district: 'Munnar',
    hasDetails: true,
  },
  {
    id: 'idukki_munnar_kundala_lake',
    name: 'Kundala Lake',
    description: 'Famous for Kashmiri-style Shikara rides and seasonal cherry blossoms.',
    location: 'Munnar',
    imageId: 'attraction-kundala-lake',
    district: 'Munnar',
    hasDetails: true,
  },
  {
    id: 'idukki_munnar_tea_museum',
    name: 'Tata Tea Museum',
    description: 'Showcases the legacy of tea plantations in Munnar with machinery and artifacts.',
    location: 'Munnar',
    imageId: 'attraction-tea-museum',
    district: 'Munnar',
    hasDetails: true,
  },
  {
    id: 'idukki_munnar_attukad_waterfalls',
    name: 'Attukad Waterfalls',
    description: 'A picturesque waterfall nestled amidst rolling hills, perfect for trekking.',
    location: 'Munnar',
    imageId: 'attraction-attukad-waterfalls',
    district: 'Munnar',
    hasDetails: true,
  },
  {
    id: 'idukki_munnar_anamudi_peak',
    name: 'Anamudi Peak',
    description: 'The highest peak in South India, visible from Eravikulam National Park.',
    location: 'Munnar',
    imageId: 'attraction-anamudi-peak',
    district: 'Munnar',
    hasDetails: true,
  },
  {
    id: 'idukki_munnar_pothamedu_viewpoint',
    name: 'Pothamedu Viewpoint',
    description: 'Offers panoramic views of tea, coffee, and cardamom plantations, great for sunsets.',
    location: 'Munnar',
    imageId: 'attraction-pothamedu-viewpoint',
    district: 'Munnar',
    hasDetails: true,
  },
  {
    id: 'idukki_munnar_chokramudi_peak',
    name: 'Chokramudi Peak',
    description: 'A popular trekking spot offering breathtaking views of the Idukki landscape.',
    location: 'Munnar',
    imageId: 'attraction-chokramudi-peak',
    district: 'Munnar',
    hasDetails: true,
  },
];

export const diningOptions: Item[] = [
  {
    id: '1',
    name: 'Kerala Sadya',
    description: 'A traditional vegetarian feast served on a banana leaf, featuring a wide array of dishes.',
    location: 'Statewide',
    imageId: 'dining-sadya',
    district: 'Various',
  },
  {
    id: '2',
    name: 'Puttu and Kadala Curry',
    description: 'A classic breakfast combination of steamed rice and coconut cylinders served with black chickpea curry.',
    location: 'Statewide',
    imageId: 'dining-puttu',
    district: 'Various',
  },
  {
    id: '3',
    name: 'Karimeen Pollichathu',
    description: 'Pearl spot fish marinated in spices, wrapped in a banana leaf and grilled to perfection. A backwater delicacy.',
    location: 'Alleppey, Kumarakom',
    imageId: 'dining-seafood',
    district: 'Alappuzha',
  },
];


export const accommodations: Item[] = [
  {
    id: '1',
    name: 'Taj Malabar Resort & Spa',
    description: 'A luxurious 5-star resort in Kochi offering stunning harbor views, a beautiful pool, and a blend of modern and traditional architecture.',
    location: 'Willingdon Island, Kochi',
    imageId: 'accommodation-luxury',
    district: 'Kochi',
  },
  {
    id: '2',
    name: 'Marari Beach Resort',
    description: 'An eco-friendly resort in Alappuzha, designed like a traditional fishing village. It offers private cottages, an ayurvedic spa, and direct beach access.',
    location: 'Mararikulam, Alappuzha',
    imageId: 'accommodation-homestay',
    district: 'Alappuzha',
  },
  {
    id: '3',
    name: 'Rainforest Boutique Resort',
    description: 'A unique resort located at the base of the Athirapally falls in Thrissur, offering breathtaking views and a tranquil forest experience with treehouse options.',
    location: 'Athirapally, Thrissur',
    imageId: 'accommodation-treehouse',
    district: 'Thrissur',
  },
];
